name: ci
on:
  push:
    branches-ignore:
      - 'ghc-next*'
      - 'ghc-9.12*'
  pull_request:
    branches-ignore:
      - 'ghc-next*'
  schedule:
  - cron:  '0 3 * * 6' # 3am Saturday
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ghc: ['9.12', '9.10', '9.8']
        include:
        - os: windows-latest
          ghc: '9.12'
        - os: macOS-latest
          ghc: '9.12'
    steps:
    - run: git config --global core.autocrlf false
    - uses: actions/checkout@v2
    - uses: haskell-actions/setup@v2
      id: setup-haskell
      with:
        ghc-version: ${{ matrix.ghc }}
    - run: cabal install apply-refact --install-method=copy
      # Not available on GHC 9.10, see https://github.com/mpickering/apply-refact/pull/149
      if: matrix.ghc == '9.12' || matrix.ghc == '9.8'
    - name: Get GHC libdir
      id: get-ghc-libdir
      run: echo "libdir=$(ghc --print-libdir)" >> $GITHUB_OUTPUT
      shell: bash
    - run: cabal v2-freeze --enable-tests
    - uses: actions/cache@v2
      with:
        path: ${{ steps.setup-haskell.outputs.cabal-store }}
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ steps.get-ghc-libdir.outputs.libdir }}-${{ hashFiles('cabal.project.freeze') }}
    - uses: ndmitchell/neil@master
      with:
        hlint-arguments: src
